version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - cd react-app
      - npm install

  build:
    commands:
      - npm run build
      - cd build
      - aws s3 sync . s3://${S3_BUCKET} --delete

  post_build:
    commands:
      - aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_DISTRIBUTION_ID} --paths "/*"

artifacts:
  files:
    - '**/*'
  base-directory: 'react-app/build' 